#!/usr/bin/env bash
if [ -f /usr/bin/apt-get ]; then
    apt-get -y install ack-grep git-core vim
fi

if [ -f /usr/bin/yum ]; then
    yum install -y git-core
fi

# Do homeshick bootstrap
if [ ! -d /home/vagrant/.homesick ]; then
    su -c "git clone git://github.com/andsens/homeshick.git /home/vagrant/.homesick/repos/homeshick" vagrant
    su -c "source /home/vagrant/.homesick/repos/homeshick/homeshick.sh && yes no| homeshick clone aarcro/dotfiles" vagrant
fi
